### ISSUE TITLE
Ability to run with reduced privileges

### ISSUE THREAD

**Issue by schildbach** [dovecot/docker#12]
The 2.3.21.1 docker image used to work with these reduced privileges:

```
    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT
      - CHOWN
      - SETGID
      - SETUID
      - KILL
    security_opt:
      - "no-new-privileges"
```

2.4.0 doesn't run any more like this:

```
[FATAL tini (7)] exec /dovecot/sbin/dovecot failed: Operation not permitted
```

What operation is not permitted?

It would be nice if a section would be added to the readme (e.g. at Docker hub) that described which capabilities can be dropped, or which need to be retained – and perhaps also why they're needed.
