### ISSUE TITLE
/srv/mail and /srv/vmail is empty

### ISSUE THREAD

**Issue by hartmark** [dovecot/docker#26]
I'm running dovecot on a old server lacking AVX so I had to build my own image.

I have this docker-compose.yml:
```
% cat docker-compose.yaml 
services:
  dovecot:
# 2.4.1 now needs AVX-support
    image: dovecot/dovecot:2.4.1-amd64
    ports:
      - '31993:31993'
    restart: always
    volumes:
     - ./cert/:/etc/dovecot/ssl
     - ./conf.d/:/etc/dovecot/conf.d
     - ${MAIL_ROOT}/mail:/srv/mail
     - ${MAIL_ROOT}/vmail:/srv/vmail
      - ./logs/dovecot:/var/log/dovecot
    environment:
      - USER_PASSWORD=${USER_PASSWORD}
      - DOVEADM_PASSWORD=${DOVEADM_PASSWORD}

```
```
% cat .env 
USER_PASSWORD=******************
DOVEADM_PASSWORD=*********************
MAIL_ROOT=/home/markus/.dockerdata
DOCKER_USER=962
DOCKER_GROUP=100
```

There's a couple of gigabytes of mails but it doesn't show up when I check usage:
```
% du -sh /home/markus/.dockerdata/*
0       /home/markus/.dockerdata/mail
32K     /home/markus/.dockerdata/vmail
```

It seems that dovecot uses /srv/vmail folder so it's strange I don't see it outside the docker container.

`dovecot-1  | Apr 10 11:44:02 imap(markus)<21><Zgw2GmsywpCsEwAB>: Debug: index: root=/srv/vmail/markus/mail, index=, indexpvt=, control=, inbox=, alt=`
